[package]
name = "malaga"
version = "0.1.0"
authors = ["spieljs <spieljs@gmail.com>"]
edition = "2018"

[dependencies]
malaga_http_utils = "0.1"
lapin-futures = "0.25.0"
futures = "0.1"
log = "0.4.8"
serde_json= "1.0"
tower-web= "0.3"
tokio= "0.1"